# Generated by Django 4.2 on 2023-04-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupin', '0002_registermodel_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='usertype',
            field=models.CharField(choices=[('Patient', 'PATIENT'), ('Doctor', 'DOCTOR')], default='Patient', max_length=20),
        ),
    ]
