# Generated by Django 4.2 on 2023-04-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupin', '0003_alter_registermodel_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='Pincode',
        ),
    ]
