# Generated by Django 4.2 on 2023-04-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupin', '0004_remove_registermodel_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('Patient', 'PATIENT'), ('Doctor', 'DOCTOR')], default='Patient', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='usertype',
        ),
    ]
