# Generated by Django 4.1 on 2023-04-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupin', '0008_signregmodel_utmodel_remove_signupmodel_user_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='profilepic/')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SignRegModel',
        ),
    ]
