# Generated by Django 4.1 on 2023-04-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupin', '0009_signupmodel_delete_signregmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='confirm_password',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='password',
            field=models.CharField(max_length=8),
        ),
    ]
