# Generated by Django 4.1 on 2023-04-20 14:42

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signupin', '0010_alter_signupmodel_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signupmodel',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='signupmodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='profile_pic',
            new_name='ProfilePic',
        ),
        migrations.RemoveField(
            model_name='signupmodel',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='signupmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signupmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='signupmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='signupmodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='signupmodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='signupmodel',
            name='username',
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='ConfirmPassword',
            field=models.CharField(default=datetime.datetime(2023, 4, 20, 14, 42, 37, 242640, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
